name: Build and Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev libpodofo-dev libqpdf-dev cmake build-essential tar

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build

    - name: Archive Application
      run: tar -czf PDFEditor-linux-x86_64.tar.gz -C build PDFEditor

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: PDFEditor-linux-x86_64.tar.gz

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-cmake
          mingw-w64-ucrt-x86_64-make
          mingw-w64-ucrt-x86_64-qt6-base
          mingw-w64-ucrt-x86_64-qt6-tools
          mingw-w64-ucrt-x86_64-podofo
          mingw-w64-ucrt-x86_64-qpdf
          mingw-w64-ucrt-x86_64-pkgconf
          zip

    - name: Configure CMake
      run: cmake -B build -S . -G "MinGW Makefiles"

    - name: Build
      run: cmake --build build

    - name: Archive Application
      run: |
        mkdir release_dir
        cp build/PDFEditor.exe release_dir/
        cd release_dir
        windeployqt --release --no-compiler-runtime --no-translations PDFEditor.exe
        for dll in $(find . -type f \( -name "*.exe" -o -name "*.dll" \) -exec ldd {} + | awk '/=>/ {print $3} !/=>/ {print $1}' | grep -iE 'ucrt64.*\.dll' | tr -d '\r' | sort -u); do cp -f "$dll" . ; done
        rm -f D3Dcompiler_47.dll opengl32sw.dll
        zip -r ../PDFEditor-windows-x86_64.zip *

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: PDFEditor-windows-x86_64.zip

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/PDFEditor-linux-x86_64.tar.gz
          artifacts/PDFEditor-windows-x86_64.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
